// 译林版英语单词库（2024新版，三年级起点）
// 数据来源：教材配套知识清单（Unit1-Unit8单词表）
// 仅收录核心词汇，不含 * 拓展词
var wordBank = {
  "3A": {
    label: "三年级上册",
    semester: "上册",
    grade: 3,
    units: [
      {
        unit: "Unit 1 Hello!",
        words: [
          { en: "hello", zh: "哈啰，你好" },
          { en: "hi", zh: "喂，嗨" },
          { en: "Good morning.", zh: "早上好。" },
          { en: "I", zh: "我" },
          { en: "am", zh: "是" },
          { en: "I\'m=I am", zh: "我是" },
          { en: "ah", zh: "啊" },
          { en: "a", zh: "一（个)" },
          { en: "cat", zh: "猫" },
          { en: "Miss", zh: "小姐，女士" },
          { en: "Good afternoon.", zh: "下午好。" },
          { en: "class", zh: "同学们" },
          { en: "goodbye", zh: "再见，再会" },
          { en: "bye", zh: "再见，再会" },
        ]
      },
      {
        unit: "Unit 2 What's your name?",
        words: [
          { en: "what", zh: "什么" },
          { en: "is", zh: "是" },
          { en: "what\'s=what is", zh: "什么是" },
          { en: "your", zh: "你的，你们的" },
          { en: "name", zh: "名字" },
          { en: "my", zh: "我的" },
          { en: "Nice to meet you!", zh: "很高兴认识你！" },
          { en: "too", zh: "也" },
          { en: "boy", zh: "男孩" },
          { en: "and", zh: "和，与" },
          { en: "girl", zh: "女孩" },
          { en: "Mr(AmE Mr.)", zh: "先生" },
        ]
      },
      {
        unit: "Unit 3 Are you Su Hai?",
        words: [
          { en: "are", zh: "是" },
          { en: "you", zh: "你，你们" },
          { en: "no", zh: "不，不是" },
          { en: "not", zh: "不，没有" },
          { en: "yes", zh: "是，对" },
          { en: "Here I am!", zh: "我在这里!" },
          { en: "but", zh: "但是" },
          { en: "sorry", zh: "对不起" },
          { en: "we", zh: "我们" },
          { en: "class", zh: "班级" },
          { en: "in", zh: "在…内，在……中" },
          { en: "with", zh: "和……在一起" },
          { en: "right", zh: "正确的" },
        ]
      },
      {
        unit: "Unit 4 This is my friend",
        words: [
          { en: "this", zh: "这，这个" },
          { en: "friend", zh: "朋友" },
          { en: "she", zh: "她" },
          { en: "she\'s =she is", zh: "她是" },
          { en: "he", zh: "他" },
          { en: "he\'s=he is", zh: "他是" },
          { en: "it", zh: "它" },
          { en: "it\'s=it is", zh: "它是" },
          { en: "good", zh: "好的" },
          { en: "Thank you.", zh: "谢谢你。" },
          { en: "have", zh: "有，持有" },
          { en: "many", zh: "许多" },
        ]
      },
      {
        unit: "Unit 5 She's my mother",
        words: [
          { en: "mother", zh: "母亲，妈妈" },
          { en: "father", zh: "父亲，爸爸" },
          { en: "dad", zh: "爸爸" },
          { en: "Mum (AmE mom)", zh: "妈妈" },
          { en: "brother", zh: "哥哥，弟弟" },
          { en: "baby", zh: "婴儿" },
          { en: "sister", zh: "姐姐，妹妹" },
          { en: "Good evening.", zh: "晚上好。" },
          { en: "look", zh: "看，瞧" },
          { en: "the", zh: "这个，这些，那个，那些" },
          { en: "who", zh: "谁，什么人" },
          { en: "who\'s =who is", zh: "谁是" },
          { en: "great", zh: "好极的，好,棒的" },
          { en: "come", zh: "来" },
          { en: "meet", zh: "相识，结识，被引见介绍(给某人)" },
          { en: "family", zh: "家，家庭" },
          { en: "say", zh: "说" },
        ]
      },
      {
        unit: "Unit 6 Is he your grandpa?",
        words: [
          { en: "grandpa (grandfather)", zh: "祖父，外祖父" },
          { en: "uncle", zh: "舅父，叔父，伯父，姑父，姨父" },
          { en: "aunt", zh: "姑母，姨母，伯母，婶母，舅母" },
          { en: "grandmother (grandma)", zh: "祖母，外祖母" },
          { en: "cousin", zh: "堂兄(弟)，堂姐(妹)，表兄(弟)，表姐(妹)" },
          { en: "cool", zh: "妙极的，酷的" },
          { en: "me", zh: "我" },
          { en: "big", zh: "大的" },
          { en: "isn\'t=is not", zh: "不是" },
          { en: "it", zh: "指婴儿，尤指性别不详者" },
          { en: "happy", zh: "感到快乐的，高兴的" },
          { en: "love", zh: "爱，热爱" },
        ]
      },
      {
        unit: "Unit 7 Happy Birthday!",
        words: [
          { en: "Happy Birthday!", zh: "生日快乐!" },
          { en: "one", zh: "一" },
          { en: "two", zh: "二" },
          { en: "three", zh: "三" },
          { en: "four", zh: "四" },
          { en: "five", zh: "五" },
          { en: "six", zh: "六" },
          { en: "seven", zh: "七" },
          { en: "eight", zh: "八" },
          { en: "nine", zh: "九" },
          { en: "ten", zh: "十" },
          { en: "now", zh: "现在，此刻" },
          { en: "want", zh: "要，想要" },
          { en: "car", zh: "小汽车，轿车" },
          { en: "book", zh: "书" },
          { en: "ball", zh: "球" },
          { en: "cake", zh: "蛋糕，糕饼" },
          { en: "How lovely!", zh: "真可爱!" },
          { en: "Can I help you?", zh: "你要买什么?" },
          { en: "Yes, please", zh: "好的，谢谢。" },
          { en: "some", zh: "一些" },
          { en: "toy", zh: "玩具" },
          { en: "for", zh: "给，对，供" },
          { en: "OK", zh: "对，好，行" },
          { en: "How old are you?", zh: "你多大了?" },
          { en: "please", zh: "请" },
          { en: "here", zh: "到这里，在这里" },
          { en: "love", zh: "喜好，喜爱" },
          { en: "Here you are.", zh: "给你。" },
          { en: "You\'re welcome.", zh: "别客气。不用谢。" },
          { en: "thanks", zh: "谢谢" },
        ]
      },
      {
        unit: "Unit 8 I can do this for you",
        words: [
          { en: "can", zh: "能，会" },
          { en: "do", zh: "做，干，办(某事)" },
          { en: "for", zh: "为了" },
          { en: "clean", zh: "使......干净，打扫" },
          { en: "table", zh: "桌子" },
          { en: "draw", zh: "画，描画" },
          { en: "sing", zh: "唱(歌)，演唱" },
          { en: "take pictures", zh: "拍照" },
          { en: "dance", zh: "跳舞" },
          { en: "Are you OK?", zh: "你没事吧?" },
          { en: "picture", zh: "图画，绘画；照片" },
          { en: "of", zh: "属于(某人)，关于(某人)" },
          { en: "on", zh: "在(某一天)" },
          { en: "child (pl.children)", zh: "儿童，小孩" },
        ]
      },
    ]
  },
  "3B": {
    label: "三年级下册",
    semester: "下册",
    grade: 3,
    units: [
      {
        unit: "Unit 1 School things",
        words: [
          { en: "school", zh: "学校" },
          { en: "pen", zh: "笔，钢笔" },
          { en: "pencil", zh: "铅笔" },
          { en: "ruler", zh: "直尺" },
          { en: "rubber", zh: "橡皮" },
          { en: "schoolbag", zh: "书包" },
          { en: "pencil case", zh: "铅笔盒，铅笔袋" },
          { en: "that", zh: "那，那个" },
          { en: "put", zh: "放，安置" },
          { en: "again", zh: "再一次，又一次" },
          { en: "long", zh: "长的" },
          { en: "Good idea!", zh: "好主意！" },
        ]
      },
      {
        unit: "Unit 2 Clean our classroom",
        words: [
          { en: "our", zh: "我们的" },
          { en: "classroom", zh: "教室，课堂" },
          { en: "close", zh: "关，关闭" },
          { en: "window", zh: "窗，窗户" },
          { en: "blackboard", zh: "黑板" },
          { en: "chair", zh: "椅子" },
          { en: "sweep", zh: "打扫，清扫" },
          { en: "floor", zh: "地板，地面" },
          { en: "let", zh: "让" },
          { en: "us", zh: "我们" },
          { en: "desk", zh: "课桌，书桌" },
          { en: "dirty", zh: "肮脏的" },
          { en: "Me too!", zh: "我也是!" },
          { en: "All right.", zh: "好的。" },
          { en: "clean", zh: "洁净的，干净的" },
          { en: "keep", zh: "(使)保持，处于" },
        ]
      },
      {
        unit: "Unit 3 School rules",
        words: [
          { en: "rule", zh: "规则，规章" },
          { en: "library", zh: "图书馆" },
          { en: "talk", zh: "说话，讲话" },
          { en: "eat", zh: "吃" },
          { en: "run", zh: "跑，奔跑" },
          { en: "Mrs (AmE Mrs.)", zh: "太太，夫人" },
          { en: "sit down", zh: "坐下" },
          { en: "late", zh: "迟的，晚的" },
          { en: "look out of", zh: "朝……外看" },
          { en: "on", zh: "在..….上面" },
          { en: "fun", zh: "有趣的" },
          { en: "quiet", zh: "安静的" },
          { en: "Would you like ... ?", zh: "你想要……吗?" },
          { en: "look at", zh: "看，瞧" },
          { en: "That\'s all right.", zh: "不要紧。" },
        ]
      },
      {
        unit: "Unit 4 Have fun after class",
        words: [
          { en: "have fun", zh: "玩得高兴" },
          { en: "after class", zh: "课后" },
          { en: "behind", zh: "在……的后而" },
          { en: "tree", zh: "树，树木" },
          { en: "by", zh: "在.…旁边" },
          { en: "under", zh: "在……下面" },
          { en: "flower", zh: "花，花朵" },
          { en: "play", zh: "玩耍" },
          { en: "go", zh: "开始;移动" },
          { en: "plane", zh: "飞机" },
          { en: "very", zh: "很，非常" },
          { en: "far", zh: "远" },
          { en: "where", zh: "在哪里，到哪里" },
          { en: "find", zh: "找到" },
          { en: "over", zh: "结束" },
          { en: "student", zh: "学生" },
          { en: "lovely", zh: "极好的;美丽的" },
          { en: "day", zh: "白天" },
          { en: "today", zh: "今天" },
          { en: "garden", zh: "花园，园圃" },
          { en: "beautiful", zh: "美丽的，美好的" },
          { en: "duck", zh: "鸭子" },
        ]
      },
      {
        unit: "Unit 5 Fruit",
        words: [
          { en: "fruit", zh: "水果" },
          { en: "orange", zh: "橙子、柑橘" },
          { en: "grape", zh: "葡萄" },
          { en: "banana", zh: "香蕉" },
          { en: "apple", zh: "苹果" },
          { en: "mango", zh: "芒果" },
          { en: "share", zh: "分享，共享" },
          { en: "like", zh: "喜欢，喜爱" },
          { en: "they", zh: "它们，他们，她们" },
          { en: "make", zh: "做，制造" },
          { en: "an", zh: "一(个)" },
          { en: "What about you?", zh: "你呢?" },
          { en: "How nice!", zh: "真好看!" },
          { en: "good", zh: "有用，有好处" },
        ]
      },
      {
        unit: "Unit 6 On the farm",
        words: [
          { en: "farm", zh: "农场" },
          { en: "rabbit", zh: "兔子" },
          { en: "cow", zh: "奶牛" },
          { en: "sheep", zh: "羊，绵羊" },
          { en: "chicken", zh: "鸡" },
          { en: "carrot", zh: "胡萝卜" },
          { en: "pig", zh: "猪" },
          { en: "Welcome to ...", zh: "欢迎米到……" },
          { en: "home", zh: "家，住所" },
          { en: "these", zh: "这些" },
          { en: "those", zh: "那些" },
          { en: "help", zh: "帮助、协助" },
          { en: "cute", zh: "可爱的" },
          { en: "move", zh: "移动" },
        ]
      },
      {
        unit: "Unit 7 Animals",
        words: [
          { en: "animal", zh: "动物" },
          { en: "bear", zh: "熊" },
          { en: "lion", zh: "狮子" },
          { en: "monkey", zh: "猴子" },
          { en: "tiger", zh: "老虎" },
          { en: "panda", zh: "大熊猫" },
          { en: "elephant", zh: "大象" },
          { en: "fish", zh: "鱼;鱼肉" },
          { en: "feed", zh: "给食物，喂养" },
          { en: "zoo", zh: "动物园" },
          { en: "go", zh: "去，走" },
          { en: "see", zh: "看，见" },
        ]
      },
      {
        unit: "Unit 8 Colours",
        words: [
          { en: "colour (AmE color)", zh: "颜色，色彩" },
          { en: "yellow", zh: "黄色的" },
          { en: "blue", zh: "蓝色的" },
          { en: "red", zh: "红色的" },
          { en: "orange", zh: "橙红色的，橘黄色的" },
          { en: "pink", zh: "粉红色的" },
          { en: "green", zh: "绿色的" },
          { en: "brown", zh: "棕色的" },
          { en: "black", zh: "黑色的" },
          { en: "white", zh: "白色的" },
          { en: "sure(表示同意)", zh: "当然" },
          { en: "What colour?", zh: "什么颜色?" },
          { en: "little", zh: "小的" },
          { en: "What colour ...?……", zh: "是什么颜色的?" },
          { en: "How come?", zh: "怎么回事?" },
        ]
      },
    ]
  },
};
